//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAPI20171114.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnchorsWorkTotal
    {
        public int Id { get; set; }
        public int AnchorId { get; set; }
        public short Year { get; set; }
        public short Month { get; set; }
        public int WorkSecond { get; set; }
        public int LastProcessWorkLogId { get; set; }
    }
}
