//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAPI20171114.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_liveOpenRecord
    {
        public int id { get; set; }
        public string code { get; set; }
        public string tableId { get; set; }
        public string liveId { get; set; }
        public int dealerId { get; set; }
        public string issueNo { get; set; }
        public int state { get; set; }
        public string openNum { get; set; }
        public System.DateTime startTime { get; set; }
        public System.DateTime endTime { get; set; }
        public System.DateTime add_time { get; set; }
        public byte[] lockid { get; set; }
    }
}
