//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAPI20171114.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_ManagerRole
    {
        public int Id { get; set; }
        public string RoleName { get; set; }
        public bool LiveCmsManage { get; set; }
        public bool DealerManage { get; set; }
        public bool DealerList { get; set; }
        public bool DealerPost { get; set; }
        public bool DealerTime { get; set; }
        public bool LiveManage { get; set; }
        public bool VideoList { get; set; }
        public bool BarrageManage { get; set; }
        public bool SystemBarrage { get; set; }
        public bool SentenceManage { get; set; }
        public bool WordsManage { get; set; }
        public bool ManualReview { get; set; }
        public bool GiftManage { get; set; }
        public bool GiftList { get; set; }
        public bool DealerTable { get; set; }
        public bool Manager { get; set; }
        public bool ManagerList { get; set; }
        public bool RoleManage { get; set; }
        public bool ManageLog { get; set; }
        public System.DateTime AddTime { get; set; }
        public bool ShieldedRecord { get; set; }
        public bool LiveNotSpeak { get; set; }
        public bool BlackWordManage { get; set; }
        public bool RealTimeBarrage { get; set; }
        public bool AllowIp { get; set; }
    }
}
