//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAPI20171114.ImageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ImageService.ImagesServiceSoap")]
    public interface ImagesServiceSoap {
        
        // CODEGEN: 訊息 SaveFileRequest 具有標頭，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestAPI20171114.ImageService.SaveFileResponse SaveFile(TestAPI20171114.ImageService.SaveFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveFile", ReplyAction="*")]
        System.Threading.Tasks.Task<TestAPI20171114.ImageService.SaveFileResponse> SaveFileAsync(TestAPI20171114.ImageService.SaveFileRequest request);
        
        // CODEGEN: 訊息 SaveFileForUURequest 具有標頭，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveFileForUU", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestAPI20171114.ImageService.SaveFileForUUResponse SaveFileForUU(TestAPI20171114.ImageService.SaveFileForUURequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveFileForUU", ReplyAction="*")]
        System.Threading.Tasks.Task<TestAPI20171114.ImageService.SaveFileForUUResponse> SaveFileForUUAsync(TestAPI20171114.ImageService.SaveFileForUURequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MySoapHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string userPwdField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserPwd {
            get {
                return this.userPwdField;
            }
            set {
                this.userPwdField = value;
                this.RaisePropertyChanged("UserPwd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveFileRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TestAPI20171114.ImageService.MySoapHeader MySoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileByteArray;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int FileLength;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string SaveToUrl;
        
        public SaveFileRequest() {
        }
        
        public SaveFileRequest(TestAPI20171114.ImageService.MySoapHeader MySoapHeader, byte[] FileByteArray, int FileLength, string SaveToUrl) {
            this.MySoapHeader = MySoapHeader;
            this.FileByteArray = FileByteArray;
            this.FileLength = FileLength;
            this.SaveToUrl = SaveToUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SaveFileResult;
        
        public SaveFileResponse() {
        }
        
        public SaveFileResponse(string SaveFileResult) {
            this.SaveFileResult = SaveFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveFileForUU", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveFileForUURequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TestAPI20171114.ImageService.MySoapHeader MySoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileByteArray;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int FileLength;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string SaveToUrl;
        
        public SaveFileForUURequest() {
        }
        
        public SaveFileForUURequest(TestAPI20171114.ImageService.MySoapHeader MySoapHeader, byte[] FileByteArray, int FileLength, string SaveToUrl) {
            this.MySoapHeader = MySoapHeader;
            this.FileByteArray = FileByteArray;
            this.FileLength = FileLength;
            this.SaveToUrl = SaveToUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveFileForUUResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveFileForUUResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SaveFileForUUResult;
        
        public SaveFileForUUResponse() {
        }
        
        public SaveFileForUUResponse(bool SaveFileForUUResult) {
            this.SaveFileForUUResult = SaveFileForUUResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImagesServiceSoapChannel : TestAPI20171114.ImageService.ImagesServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImagesServiceSoapClient : System.ServiceModel.ClientBase<TestAPI20171114.ImageService.ImagesServiceSoap>, TestAPI20171114.ImageService.ImagesServiceSoap {
        
        public ImagesServiceSoapClient() {
        }
        
        public ImagesServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImagesServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImagesServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImagesServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAPI20171114.ImageService.SaveFileResponse TestAPI20171114.ImageService.ImagesServiceSoap.SaveFile(TestAPI20171114.ImageService.SaveFileRequest request) {
            return base.Channel.SaveFile(request);
        }
        
        public string SaveFile(TestAPI20171114.ImageService.MySoapHeader MySoapHeader, byte[] FileByteArray, int FileLength, string SaveToUrl) {
            TestAPI20171114.ImageService.SaveFileRequest inValue = new TestAPI20171114.ImageService.SaveFileRequest();
            inValue.MySoapHeader = MySoapHeader;
            inValue.FileByteArray = FileByteArray;
            inValue.FileLength = FileLength;
            inValue.SaveToUrl = SaveToUrl;
            TestAPI20171114.ImageService.SaveFileResponse retVal = ((TestAPI20171114.ImageService.ImagesServiceSoap)(this)).SaveFile(inValue);
            return retVal.SaveFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestAPI20171114.ImageService.SaveFileResponse> TestAPI20171114.ImageService.ImagesServiceSoap.SaveFileAsync(TestAPI20171114.ImageService.SaveFileRequest request) {
            return base.Channel.SaveFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestAPI20171114.ImageService.SaveFileResponse> SaveFileAsync(TestAPI20171114.ImageService.MySoapHeader MySoapHeader, byte[] FileByteArray, int FileLength, string SaveToUrl) {
            TestAPI20171114.ImageService.SaveFileRequest inValue = new TestAPI20171114.ImageService.SaveFileRequest();
            inValue.MySoapHeader = MySoapHeader;
            inValue.FileByteArray = FileByteArray;
            inValue.FileLength = FileLength;
            inValue.SaveToUrl = SaveToUrl;
            return ((TestAPI20171114.ImageService.ImagesServiceSoap)(this)).SaveFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAPI20171114.ImageService.SaveFileForUUResponse TestAPI20171114.ImageService.ImagesServiceSoap.SaveFileForUU(TestAPI20171114.ImageService.SaveFileForUURequest request) {
            return base.Channel.SaveFileForUU(request);
        }
        
        public bool SaveFileForUU(TestAPI20171114.ImageService.MySoapHeader MySoapHeader, byte[] FileByteArray, int FileLength, string SaveToUrl) {
            TestAPI20171114.ImageService.SaveFileForUURequest inValue = new TestAPI20171114.ImageService.SaveFileForUURequest();
            inValue.MySoapHeader = MySoapHeader;
            inValue.FileByteArray = FileByteArray;
            inValue.FileLength = FileLength;
            inValue.SaveToUrl = SaveToUrl;
            TestAPI20171114.ImageService.SaveFileForUUResponse retVal = ((TestAPI20171114.ImageService.ImagesServiceSoap)(this)).SaveFileForUU(inValue);
            return retVal.SaveFileForUUResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestAPI20171114.ImageService.SaveFileForUUResponse> TestAPI20171114.ImageService.ImagesServiceSoap.SaveFileForUUAsync(TestAPI20171114.ImageService.SaveFileForUURequest request) {
            return base.Channel.SaveFileForUUAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestAPI20171114.ImageService.SaveFileForUUResponse> SaveFileForUUAsync(TestAPI20171114.ImageService.MySoapHeader MySoapHeader, byte[] FileByteArray, int FileLength, string SaveToUrl) {
            TestAPI20171114.ImageService.SaveFileForUURequest inValue = new TestAPI20171114.ImageService.SaveFileForUURequest();
            inValue.MySoapHeader = MySoapHeader;
            inValue.FileByteArray = FileByteArray;
            inValue.FileLength = FileLength;
            inValue.SaveToUrl = SaveToUrl;
            return ((TestAPI20171114.ImageService.ImagesServiceSoap)(this)).SaveFileForUUAsync(inValue);
        }
    }
}
